var food = [
	//START OF FIRST PAGE

	{
		"name":"Frozen Broccoli",
		"price":0.16,
		"serving_size":"10 Oz Pkg",
		"calories":73.8,
		"cholesterol_mg":0,
		"totalfat_g":0.8,
		"sodium_mg":68.2,
		"carbs_g":13.6,
		"fiber_g":8.5,
		"protein_g":8,
		"vita_iu":5867.4,
		"vitc_iu":160.2,
		"calcium_mg":159,
		"iron_mg":2.3
	},

	{
		"name":"Carrots, Raw",
		"price":0.07,
		"serving_size":"1/2 Cup Shredded",
		"calories":23.7,
		"cholesterol_mg":0,
		"totalfat_g":0.1,
		"sodium_mg":19.2,
		"carbs_g":5.6,
		"fiber_g":1.6,
		"protein_g":0.6,
		"vita_iu":15471,
		"vitc_iu":5.1,
		"calcium_mg":14.9,
		"iron_mg":0.3
	},

	{
		"name":"Celery, Raw",
		"price":0.04,
		"serving_size":"1 Stalk",
		"calories":6.4,
		"cholesterol_mg":0,
		"totalfat_g":0.1,
		"sodium_mg":34.8,
		"carbs_g":1.5,
		"fiber_g":0.7,
		"protein_g":0.3,
		"vita_iu":53.6,
		"vitc_iu":2.8,
		"calcium_mg":16,
		"iron_mg":0.2
	},

	{
		"name":"Frozen Corn",
		"price":0.18,
		"serving_size":"1/2 Cup",
		"calories":72.2,
		"cholesterol_mg":0,
		"totalfat_g":0.6,
		"sodium_mg":2.5,
		"carbs_g":17.1,
		"fiber_g":2,
		"protein_g":2.5,
		"vita_iu":106.6,
		"vitc_iu":5.2,
		"calcium_mg":3.3,
		"iron_mg":0.3
	},

	{
		"name":"Lettuce, Iceberg, Raw",
		"price":0.02,
		"serving_size":"1 Leaf",
		"calories":2.6,
		"cholesterol_mg":0,
		"totalfat_g":0,
		"sodium_mg":1.8,
		"carbs_g":0.4,
		"fiber_g":0.3,
		"protein_g":0.2,
		"vita_iu":66,
		"vitc_iu":0.8,
		"calcium_mg":3.8,
		"iron_mg":0.1
	},

	{
		"name":"Peppers, Sweet, Raw",
		"price":0.53,
		"serving_size":"1 Pepper",
		"calories":20,
		"cholesterol_mg":0,
		"totalfat_g":0.1,
		"sodium_mg":1.5,
		"carbs_g":4.8,
		"fiber_g":1.3,
		"protein_g":0.7,
		"vita_iu":467.7,
		"vitc_iu":66.1,
		"calcium_mg":6.7,
		"iron_mg":0.3
	},

	{
		"name":"Potatoes, Baked",
		"price":0.06,
		"serving_size":"1/2 Cup",
		"calories":171.5,
		"cholesterol_mg":0,
		"totalfat_g":0.2,
		"sodium_mg":15.2,
		"carbs_g":39.9,
		"fiber_g":3.2,
		"protein_g":3.7,
		"vita_iu":0,
		"vitc_iu":15.6,
		"calcium_mg":22.7,
		"iron_mg":4.3
	},

	{
		"name":"Tofu",
		"price":0.31,
		"serving_size":"1/4 block",
		"calories":88.2,
		"cholesterol_mg":0,
		"totalfat_g":5.5,
		"sodium_mg":8.1,
		"carbs_g":2.2,
		"fiber_g":1.4,
		"protein_g":9.4,
		"vita_iu":98.6,
		"vitc_iu":0.1,
		"calcium_mg":121.8,
		"iron_mg":6.2
	},

	{
		"name":"Roasted Chicken",
		"price":0.84,
		"serving_size":"1 lb chicken",
		"calories":277.4,
		"cholesterol_mg":129.9,
		"totalfat_g":10.8,
		"sodium_mg":125.6,
		"carbs_g":0,
		"fiber_g":0,
		"protein_g":42.2,
		"vita_iu":77.4,
		"vitc_iu":0,
		"calcium_mg":21.9,
		"iron_mg":1.8
	},

	{
		"name":"Spaghetti w/ sauce",
		"price":0.78,
		"serving_size":"1 1/2 Cup",
		"calories":358.2,
		"cholesterol_mg":0,
		"totalfat_g":12.3,
		"sodium_mg":1237.1,
		"carbs_g":58.3,
		"fiber_g":11.6,
		"protein_g":8.2,
		"vita_iu":3055.2,
		"vitc_iu":27.9,
		"calcium_mg":80.2,
		"iron_mg":2.3
	},

	{
		"name":"Tomato, Red, Ripe, Raw",
		"price":0.27,
		"serving_size":"1 Tomato, 2-3/5 In",
		"calories":25.8,
		"cholesterol_mg":0,
		"totalfat_g":0.4,
		"sodium_mg":11.1,
		"carbs_g":5.7,
		"fiber_g":1.4,
		"protein_g":1,
		"vita_iu":766.3,
		"vitc_iu":23.5,
		"calcium_mg":6.2,
		"iron_mg":0.6
	},

	{
		"name":"Apple, Raw, W/ Skin",
		"price":0.24,
		"serving_size":"1 Fruit, 3/Lb, Wo/Rf",
		"calories":81.4,
		"cholesterol_mg":0,
		"totalfat_g":0.5,
		"sodium_mg":0,
		"carbs_g":21,
		"fiber_g":3.7,
		"protein_g":0.3,
		"vita_iu":73.1,
		"vitc_iu":7.9,
		"calcium_mg":9.7,
		"iron_mg":0.2
	},

	{
		"name":"Banana",
		"price":0.15,
		"serving_size":"1 Fruit, Wo/Skin&Seeds",
		"calories":104.9,
		"cholesterol_mg":0,
		"totalfat_g":0.5,
		"sodium_mg":1.1,
		"carbs_g":26.7,
		"fiber_g":2.7,
		"protein_g":1.2,
		"vita_iu":92.3,
		"vitc_iu":10.4,
		"calcium_mg":6.8,
		"iron_mg":0.4
	},

	{
		"name":"Grapes",
		"price":0.32,
		"serving_size":"10 Fruits, Wo/Rf",
		"calories":15.1,
		"cholesterol_mg":0,
		"totalfat_g":0.1,
		"sodium_mg":0.5,
		"carbs_g":4.1,
		"fiber_g":0.2,
		"protein_g":0.2,
		"vita_iu":24,
		"vitc_iu":1,
		"calcium_mg":3.4,
		"iron_mg":0.1
	},

	{
		"name":"Kiwifruit, Raw, Fresh",
		"price":0.49,
		"serving_size":"1 Med Frt, Wo/Skin",
		"calories":46.4,
		"cholesterol_mg":0,
		"totalfat_g":0.3,
		"sodium_mg":3.8,
		"carbs_g":11.3,
		"fiber_g":2.6,
		"protein_g":0.8,
		"vita_iu":133,
		"vitc_iu":74.5,
		"calcium_mg":19.8,
		"iron_mg":0.3
	},

	// START OF SECOND PAGE

	{
		"name":"Oranges",
		"price":0.15,
		"serving_size":"1 Frt, 2-5/8 Diam",
		"calories":61.6,
		"cholesterol_mg":0,
		"totalfat_g":0.2,
		"sodium_mg":0,
		"carbs_g":15.4,
		"fiber_g":3.1,
		"protein_g":1.2,
		"vita_iu":268.6,
		"vitc_iu":69.7,
		"calcium_mg":52.4,
		"iron_mg":0.1
	},

	{
		"name":"Bagels",
		"price":0.16,
		"serving_size":"1 Oz",
		"calories":78,
		"cholesterol_mg":0,
		"totalfat_g":0.5,
		"sodium_mg":151.4,
		"carbs_g":15.1,
		"fiber_g":0.6,
		"protein_g":3,
		"vita_iu":0,
		"vitc_iu":0,
		"calcium_mg":21,
		"iron_mg":1
	},

	{
		"name":"Wheat Bread",
		"price":0.05,
		"serving_size":"1 Sl",
		"calories":65,
		"cholesterol_mg":0,
		"totalfat_g":1,
		"sodium_mg":134.5,
		"carbs_g":12.4,
		"fiber_g":1.3,
		"protein_g":2.2,
		"vita_iu":0,
		"vitc_iu":0,
		"calcium_mg":10.8,
		"iron_mg":0.7
	},

	{
		"name":"White Bread",
		"price":0.06,
		"serving_size":"1 Sl",
		"calories":65,
		"cholesterol_mg":0,
		"totalfat_g":1,
		"sodium_mg":132.5,
		"carbs_g":11.8,
		"fiber_g":1.1,
		"protein_g":2.3,
		"vita_iu":0,
		"vitc_iu":0,
		"calcium_mg":26.2,
		"iron_mg":0.8
	},

	{
		"name":"Oatmeal Cookies",
		"price":0.09,
		"serving_size":"1 Cookie",
		"calories":81,
		"cholesterol_mg":0,
		"totalfat_g":3.3,
		"sodium_mg":68.9,
		"carbs_g":12.4,
		"fiber_g":0.6,
		"protein_g":1.1,
		"vita_iu":2.9,
		"vitc_iu":0.1,
		"calcium_mg":6.7,
		"iron_mg":0.5
	},

	{
		"name":"Apple Pie",
		"price":0.16,
		"serving_size":"1 Oz",
		"calories":67.2,
		"cholesterol_mg":0,
		"totalfat_g":3.1,
		"sodium_mg":75.4,
		"carbs_g":9.6,
		"fiber_g":0.5,
		"protein_g":0.5,
		"vita_iu":35.2,
		"vitc_iu":0.9,
		"calcium_mg":3.1,
		"iron_mg":0.1
	},

	{
		"name":"Chocolate Chip Cookies",
		"price":0.03,
		"serving_size":"1 Cookie",
		"calories":78.1,
		"cholesterol_mg":5.1,
		"totalfat_g":4.5,
		"sodium_mg":57.8,
		"carbs_g":9.3,
		"fiber_g":0,
		"protein_g":0.9,
		"vita_iu":101.8,
		"vitc_iu":0,
		"calcium_mg":6.2,
		"iron_mg":0.4
	},

	{
		"name":"Butter, Regular",
		"price":0.05,
		"serving_size":"1 Pat",
		"calories":35.8,
		"cholesterol_mg":10.9,
		"totalfat_g":4.1,
		"sodium_mg": 41.3,
		"carbs_g":0,
		"fiber_g":0,
		"protein_g":0,
		"vita_iu":152.9,
		"vitc_iu":0,
		"calcium_mg":1.2,
		"iron_mg":0
	},

	{
		"name":"Cheddar Cheese",
		"price":0.25,
		"serving_size":"1 Oz",
		"calories":112.7,
		"cholesterol_mg":29.4,
		"totalfat_g":9.3,
		"sodium_mg":173.7,
		"carbs_g":0.4,
		"fiber_g":0,
		"protein_g":7,
		"vita_iu":296.5,
		"vitc_iu":0,
		"calcium_mg":202,
		"iron_mg":0.2
	},

	{
		"name":"3.3% Fat, Whole Milk",
		"price":0.16,
		"serving_size":"1 C",
		"calories":149.9,
		"cholesterol_mg":33.2,
		"totalfat_g":8.1,
		"sodium_mg":119.6,
		"carbs_g":11.4,
		"fiber_g":0,
		"protein_g":8,
		"vita_iu":307.4,
		"vitc_iu":2.3,
		"calcium_mg":291.3,
		"iron_mg":0.1
	},
]

/*
	{
		"name":"",
		"price":,
		"serving_size":"",
		"calories":,
		"cholesterol_mg":,
		"totalfat_g":,
		"sodium_mg":,
		"carbs_g":,
		"fiber_g":,
		"protein_g":,
		"vita_iu":,
		"vitc_iu":,
		"calcium_mg":,
		"iron_mg":
	},
*/